### ISSUE TITLE
Benefits.mdx duplicate words

### ISSUE THREAD

**Issue by ethisscam** [friends-with-benefits/fwb-wiki#33]
From [Benefits](https://github.com/friends-with-benefits/fwb-wiki/blob/main/pages/Benefits.mdx) it said
> FWB has different pockets of cultures & scenes — from fashion, to design, to music, to degen, to mental health, to NFTs, degen, skincare, local food, filmmakers, and so much more. 

Seems **degen** appears twice. Is it right?

**Comment by rubythelot** [comment]
Fixed! Thank you so much for the feedback
